import type {
  EvidenceKey,
  GateType,
  MacroCycle,
  OperatingMode,
  RiskClass,
} from "../types/canonical.js";
import { GATE_TYPES, MACRO_CYCLES, OPERATING_MODES, RISK_CLASSES } from "../types/canonical.js";

export type CatalogApplicability = "mandatory" | "optional" | "skipped";

export interface CatalogActivation {
  readonly macroCycles: readonly MacroCycle[];
  readonly gateTypes?: readonly GateType[];
  readonly riskClasses: readonly RiskClass[];
  readonly operatingModes?: readonly OperatingMode[];
  readonly keywords: readonly string[];
  readonly auto: boolean;
}

export interface SkillCatalogEntry {
  readonly id: string;
  readonly title: string;
  readonly purpose: string;
  readonly activation: CatalogActivation;
  readonly procedure?: readonly string[];
  readonly owns: readonly string[];
  readonly outOfScope: readonly string[];
  readonly evidenceProduced: readonly EvidenceKey[];
  readonly hookRefs: readonly string[];
  readonly subagentRefs: readonly string[];
}

export interface HookCatalogEntry {
  readonly id: string;
  readonly title: string;
  readonly purpose: string;
  readonly macroCycles: readonly MacroCycle[];
  readonly gateTypes: readonly GateType[];
  readonly riskClasses: readonly RiskClass[];
  readonly operatingModes: readonly OperatingMode[];
  readonly evidenceKeys: readonly EvidenceKey[];
  readonly skillRefs: readonly string[];
  readonly subagentRefs: readonly string[];
}

export interface SubagentCatalogEntry {
  readonly id: string;
  readonly title: string;
  readonly purpose: string;
  readonly spawn: {
    readonly macroCycles: readonly MacroCycle[];
    readonly gateTypes: readonly GateType[];
    readonly minimumRiskClass: RiskClass;
    readonly applicabilityByRisk: Readonly<Record<RiskClass, CatalogApplicability>>;
    readonly operatingModes?: readonly OperatingMode[];
  };
  readonly evidenceProduced: readonly EvidenceKey[];
  readonly hookRefs: readonly string[];
  readonly skillRefs: readonly string[];
  readonly maxParallelSafe: number;
}

export interface OperationalCatalog {
  readonly skills: readonly SkillCatalogEntry[];
  readonly hooks: readonly HookCatalogEntry[];
  readonly subagents: readonly SubagentCatalogEntry[];
}

const ALL_CYCLES = MACRO_CYCLES;
const ALL_GATES = GATE_TYPES;
const ALL_RISKS = RISK_CLASSES;
const ALL_MODES = OPERATING_MODES;
const GOVERNED_RISKS = ["M", "H", "C"] as const satisfies readonly RiskClass[];
const GOVERNED_MODES = ["auto", "pairing"] as const satisfies readonly OperatingMode[];

const OPERATIONAL_CATALOG = {
  skills: [
    {
      id: "hima-enter",
      title: "HIMA Enter",
      purpose:
        "Start a governed HIMA development session from an idea, select the operating mode, and bind the route before implementation.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "hima",
          "enter",
          "start development",
          "development mode",
          "mode developpement",
          "governed development",
        ],
        auto: true,
      },
      procedure: [
        "Use this skill as the first explicit step before governed implementation work. Do not depend on OMX, external workflow skills, or manual edits to `.planning/`.",
        "",
        "1. Decide whether the user is asking for development. If the request is only chat, research, explanation, or status, do not enter `build/Execute`; report status instead.",
        "2. Choose one operating mode: `bypass` for T/L low-friction work only, `auto` as the default autonomous development mode, or `pairing` when the user wants checkpoints or the risk is H/C.",
        '3. Classify risk with the kernel command. Prefer higher risk when uncertain. Example: `harness risk classify --files "src/foo.ts" --linesChanged 120 --confidence medium --json`.',
        '4. Enter the route through the kernel, not by editing files: `harness enter --root . --phase build --subPhase Execute --mode auto --riskClass M --objective "short objective" --json`.',
        "5. If `harness` is not on PATH inside this repository, use `node packages/cli/dist/index.js` with the same arguments.",
        "6. Verify before writing: `harness status --root . --json` and `harness runtime assess-route --root . --json`.",
        "7. Start implementation only after the route, risk class, operating mode, and runtime bindings are visible. Keep writes inside allowed zones from hook context.",
      ],
      owns: [
        "development session entry",
        "operating mode selection",
        "risk-to-route binding",
        "initial verification commands",
      ],
      outOfScope: [
        "manual .planning edits",
        "OMX workflow dependency",
        "implementation before route activation",
        "silent risk downgrades",
      ],
      evidenceProduced: ["hook_decision", "confidence_level", "risk_remaining"],
      hookRefs: ["state-machine", "risk-classification", "runtime-bindings", "gate-policy"],
      subagentRefs: [],
    },
    {
      id: "classify-risk",
      title: "Classify Risk",
      purpose: "Assign a canonical T/L/M/H/C risk class and operating mode to each intent.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: ["classify", "risk", "intent"],
        auto: true,
      },
      owns: ["risk classification", "forcing signal scan", "operating mode selection"],
      outOfScope: ["cycle transition", "implementation", "evidence sufficiency evaluation"],
      evidenceProduced: ["confidence_level", "risk_remaining"],
      hookRefs: ["risk-classification"],
      subagentRefs: [],
    },
    {
      id: "propose-change",
      title: "Propose Change",
      purpose: "Convert a classified request into scoped objective, exclusions, and done criteria.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: ["propose", "change", "feature", "fix"],
        auto: true,
      },
      owns: ["intent set", "scope in/out", "definition of done", "cycle routing"],
      outOfScope: ["code changes", "deployment", "subagent execution"],
      evidenceProduced: ["files_modified", "known_gap"],
      hookRefs: ["state-machine", "gate-policy"],
      subagentRefs: [],
    },
    {
      id: "transition-phase",
      title: "Transition Phase",
      purpose: "Guard cycle movement with state-machine and evidence checks.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["post_tool", "stop"],
        riskClasses: GOVERNED_RISKS,
        operatingModes: GOVERNED_MODES,
        keywords: ["advance", "next cycle", "promote", "transition"],
        auto: true,
      },
      owns: ["state transition", "exit condition check", "missing evidence report"],
      outOfScope: ["artifact creation", "risk demotion", "runtime installation"],
      evidenceProduced: ["hook_decision", "known_gap"],
      hookRefs: ["state-machine", "convergence", "close-finalization"],
      subagentRefs: ["evidence-collector"],
    },
    {
      id: "status",
      title: "Status",
      purpose: "Read the current route, risk, state, and next action without mutation.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: ["status", "where are we", "etat"],
        auto: true,
      },
      owns: ["state snapshot", "route summary", "next action hint"],
      outOfScope: ["state mutation", "evidence mutation", "cycle transition"],
      evidenceProduced: [],
      hookRefs: ["state-machine"],
      subagentRefs: [],
    },
    {
      id: "gate-policy",
      title: "Gate Policy",
      purpose: "Evaluate lifecycle gates against risk policy, runtime bindings, and allowed scope.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ALL_GATES,
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: ["gate", "policy", "guard"],
        auto: true,
      },
      owns: ["gate decisions", "policy violations", "context injection"],
      outOfScope: ["risk scoring", "subagent implementation", "adapter-specific hook install"],
      evidenceProduced: ["hook_decision", "known_gap"],
      hookRefs: ["gate-policy", "runtime-bindings", "platform-adapters"],
      subagentRefs: ["evidence-collector"],
    },
    {
      id: "bind-runtime",
      title: "Bind Runtime",
      purpose: "Map runtime hook capabilities to canonical gate bindings.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: ["runtime", "binding", "adapter", "hook"],
        auto: true,
      },
      owns: ["runtime capability inspection", "gate binding status", "blocking capability report"],
      outOfScope: ["adapter file generation", "platform process management", "policy override"],
      evidenceProduced: ["hook_decision", "known_gap"],
      hookRefs: ["runtime-bindings", "platform-adapters"],
      subagentRefs: [],
    },
    {
      id: "build-inner-loop",
      title: "Build Inner Loop",
      purpose: "Run a risk-calibrated RED/GREEN/REFACTOR implementation loop.",
      activation: {
        macroCycles: ["build"],
        gateTypes: ["pre_tool", "post_tool"],
        riskClasses: ["L", "M", "H", "C"],
        operatingModes: ALL_MODES,
        keywords: ["build", "tdd", "implement", "code"],
        auto: false,
      },
      owns: ["test-first workflow", "minimum implementation", "focused verification"],
      outOfScope: ["release decision", "production monitoring", "human approval"],
      evidenceProduced: ["integration_tests", "command_output", "files_modified"],
      hookRefs: ["convergence", "evidence-management"],
      subagentRefs: ["test-writer", "reviewer"],
    },
    {
      id: "validate-evidence",
      title: "Validate Evidence",
      purpose: "Check whether the accepted Evidence Set is sufficient for the current risk class.",
      activation: {
        macroCycles: ["validation", "release", "run", "learning"],
        gateTypes: ["stop", "subagent_stop"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: ["evidence", "verify", "validation", "done"],
        auto: true,
      },
      owns: ["evidence sufficiency", "gap list", "final-state recommendation"],
      outOfScope: ["running tests", "writing artifacts", "approving human checkpoints"],
      evidenceProduced: ["confidence_level", "known_gap", "risk_remaining"],
      hookRefs: ["evidence-management", "close-finalization"],
      subagentRefs: ["evidence-collector", "reviewer", "security-auditor"],
    },
    {
      id: "run-monitor",
      title: "Run Monitor",
      purpose: "Track runtime health signals and trigger convergence or finalization follow-up.",
      activation: {
        macroCycles: ["run"],
        gateTypes: ["session_start", "post_tool", "stop"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: ["run", "monitor", "slo", "alert"],
        auto: false,
      },
      owns: ["operational health summary", "SLO gap detection", "run-cycle recommendation"],
      outOfScope: ["infrastructure provisioning", "incident implementation", "deployment"],
      evidenceProduced: ["command_output", "risk_remaining", "known_gap"],
      hookRefs: ["convergence", "evidence-management"],
      subagentRefs: ["perf-profiler", "evidence-collector"],
    },
    {
      id: "close-run",
      title: "Close Run",
      purpose: "Finalize a run only after evidence, policy, and runtime gates agree.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["stop"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: ["close", "final", "finish"],
        auto: true,
      },
      owns: ["final state selection", "residual risk summary", "known gap disclosure"],
      outOfScope: ["additional implementation", "silent evidence fabrication", "risk downgrade"],
      evidenceProduced: ["confidence_level", "known_gap", "risk_remaining"],
      hookRefs: ["close-finalization", "evidence-management", "gate-policy"],
      subagentRefs: ["evidence-collector"],
    },
    {
      id: "ai-ml-product-engineering",
      title: "AI/ML Product Engineering",
      purpose:
        "Use when Codex needs to design, implement, review, or evaluate AI/ML/LLM product features, including AI product fit, LLM/RAG architecture, eval plans, prompt regression, dataset quality, fine-tuning decisions, inference cost and latency, mo",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "llm",
          "rag",
          "eval",
          "hallucination",
          "ai feature",
          "model routing",
          "prompt regression",
          "fine-tuning",
          "guardrails",
          "ai trust",
          "evals",
          "vector search",
        ],
        auto: true,
      },
      owns: [
        "AI/ML product fit decisions",
        "LLM/RAG architecture decisions",
        "eval plan decisions",
        "prompt engineering decisions",
        "inference cost/latency decisions",
        "model routing decisions",
        "hallucination/guardrails decisions",
        "AI trust UX decisions",
        "fine-tuning decisions",
        "AI monitoring/drift decisions",
      ],
      outOfScope: [
        "general system architecture",
        "UX research and product flows",
        "secure SDLC/privacy",
        "product analytics instrumentation",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "api-design",
      title: "Skill: API Design",
      purpose: "machine-readable error types)",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: ["design this api", "how should i design this api"],
        auto: true,
      },
      owns: [
        "API style selection (REST / GraphQL / gRPC / tRPC) and when each is wrong",
        "API-first workflow -- design the contract before the code",
        "Resource modeling and URI design (nouns, collections, sub-resources, naming conventions)",
        "Versioning strategy (URI / header / media-type",
        "SemVer for APIs",
        "when NOT to version)",
        "Pagination",
        "filtering",
        "sorting conventions (cursor vs offset",
        "query-parameter naming)",
        "Error-contract design -- RFC 7807 / RFC 9457 Problem Details (fields",
        "extension members",
        "Idempotency for write endpoints (Idempotency-Key header, storage, expiry, replay semantics)",
        "Rate limiting and quota design (RateLimit headers, 429, Retry-After)",
        "Consumer-driven contract testing (Pact, provider verification, CI integration)",
        "Deprecation lifecycle (Deprecation + Sunset headers",
        "RFC 8594",
        "breaking-change classification",
        "Webhook design (delivery guarantees, retry with backoff, HMAC signing, consumer idempotency)",
        "API as a product (DX signals, docs-as-tests, changelog, versioned SDK alignment)",
      ],
      outOfScope: [
        "PRD / acceptance criteria / NFR layer for APIs ch.06",
        "System architecture / service boundaries / inter-service topology ch.03",
        "Authentication / authorization (OAuth 2, JWT, API keys, mTLS)",
        "Code-level function/type API ergonomics",
        "Generated-client / OpenAPI codegen quality",
        "Throughput / latency tuning (caching, CDN, connection pooling)",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "architecture-system-design",
      title: "Architecture and System Design",
      purpose: "Use this book when deciding or reviewing:",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "architecture",
          "system design",
          "decompose services",
          "scalability",
          "api design",
          "tech stack",
          "service boundary",
          "monolith",
          "microservices",
          "adr",
        ],
        auto: true,
      },
      owns: [
        "system architecture decisions",
        "service decomposition decisions",
        "data flow decisions",
        "scalability tradeoff decisions",
        "API design decisions",
        "integration topology decisions",
        "tech stack selection decisions",
      ],
      outOfScope: [
        "code maintainability and refactoring",
        "cloud/IaC/landing zone",
        "database schema/query design",
        "AI/LLM architecture specifics",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "brand-marketing-communications",
      title: "Skill: Brand, Marketing and Communications",
      purpose: "-> `10-growth/growth-distribution-excellence-book`",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "how should we position",
          "what do we stand for",
          "brand",
          "claims",
          "launch",
          "reputation",
          "brand measurement",
          "mental availability",
          "content strategy",
          "founder brand",
          "ai slop",
          "ehrenberg-bass",
        ],
        auto: true,
      },
      owns: ["Skill: Brand, Marketing and Communications decisions"],
      outOfScope: ["out-of-discipline decisions"],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "cloud-platform-infrastructure",
      title: "Cloud Platform Infrastructure",
      purpose:
        "Guide a solo founder through cloud/platform decisions: provider choice, hosting model, IAM, networking, IaC, environments, cost, resilience, observability primitives, and AI workload infrastructure.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "cloud",
          "aws",
          "gcp",
          "azure",
          "infrastructure",
          "iac",
          "terraform",
          "landing zone",
          "iam",
          "environment strategy",
          "cloud cost",
          "vpc",
          "managed service",
        ],
        auto: true,
      },
      owns: [
        "cloud landing zone decisions",
        "IAM/network topology decisions",
        "IaC decisions",
        "managed service selection decisions",
        "environment strategy decisions",
        "cost-resilience tradeoffs",
        "cloud provider choice decisions",
      ],
      outOfScope: [
        "runtime reliability/SLO",
        "database storage choices",
        "secure SDLC controls",
        "system architecture",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "code-quality-maintainability",
      title: "2026-05-17 skill note -- Shotgun Surgery / Divergent Change",
      purpose:
        "When a user asks about Shotgun Surgery, Divergent Change, scattered changes, ripple effects, co-change, broad PRs, logical coupling, Move Function, Split Phase, Inline Function, Extract Class, AI boundary cleanup or whether to split/consoli",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "refactor",
          "technical debt",
          "code review",
          "maintainability",
          "clean code",
          "dependency upgrade",
          "code smell",
          "readability",
          "dead code",
          "cognitive complexity",
        ],
        auto: true,
      },
      owns: [
        "code readability decisions",
        "refactoring decisions",
        "technical debt decisions",
        "dependency upgrade decisions",
        "documentation decisions",
        "code review decisions",
        "maintainability scoring decisions",
      ],
      outOfScope: [
        "test strategy and release confidence",
        "system architecture",
        "developer productivity tooling",
        "performance/SLO",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "concurrency-distributed-correctness",
      title: "Skill: Concurrency & Distributed Correctness",
      purpose:
        "level selection and anomaly mapping; optimistic concurrency control (version columns,",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: ["race condition", "double submit", "this transaction", "isolation level"],
        auto: true,
      },
      owns: [
        "race condition and double-submit prevention decisions",
        "database transaction isolation",
      ],
      outOfScope: ["- retry / circuit breaker / timeout / exponential backoff"],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "database-storage-performance",
      title: "Database Storage Performance",
      purpose:
        "Use this book when deciding or reviewing database/storage choices, schema/index/query design, migrations, backups, restore readiness, caching, multitenancy, performance troubleshooting, or vector/RAG storage.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "database",
          "schema",
          "index",
          "query performance",
          "migration",
          "backup",
          "postgres",
          "redis",
          "vector store",
          "caching",
          "n+1",
          "storage choice",
          "sharding",
        ],
        auto: true,
      },
      owns: [
        "database/storage choice decisions",
        "schema design decisions",
        "index/query optimization decisions",
        "migration decisions",
        "backup/restore decisions",
        "caching decisions",
        "multitenancy storage decisions",
        "vector/RAG storage decisions",
      ],
      outOfScope: [
        "cloud infrastructure/managed DB provisioning",
        "system architecture",
        "AI/RAG orchestration logic",
        "observability/SLO",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "developer-productivity-tooling",
      title: "Skill: Developer Productivity & Tooling",
      purpose:
        "(custom CLI, script, generator, template, or nothing); build and test cycle-time performance;",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "local dev loop",
          "dev loop",
          "developer experience",
          "dx",
          "build is slow",
          "should i build this tool",
          "monorepo",
          "script",
          "scaffolding",
          "ai agent workflow",
          "developer productivity",
          "onboarding",
          "dependency cache",
          "automation opportunity",
        ],
        auto: true,
      },
      owns: ["Skill: Developer Productivity & Tooling decisions"],
      outOfScope: ["out-of-discipline decisions"],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "domain-modeling-ddd",
      title: "Skill: Domain Modeling / DDD",
      purpose:
        "maintaining); subdomain identification (core / supporting / generic, and distillation);",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "model the domain",
          "bounded context",
          "aggregate design",
          "value object",
          "event storming",
          "ubiquitous language",
          "context map",
          "anemic model",
          "is ddd worth it here",
          "subdomain",
          "core domain",
          "anti-corruption layer",
          "domain event",
          "repository pattern",
          "where should the consistency boundary be",
        ],
        auto: true,
      },
      owns: ["Skill: Domain Modeling / DDD decisions"],
      outOfScope: ["out-of-discipline decisions"],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "error-handling-resilience",
      title: "Skill: Error Handling & Resilience",
      purpose: "Invoke this skill when the user asks any of the following (or close variants):",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: ["how should this fail?", "what happens when this call fails?"],
        auto: true,
      },
      owns: [
        "Error typology: programmer error vs. operational error vs. expected domain error",
        "Result/Either types vs. exceptions -- when each",
        "per language/framework",
        "Retry policy: retryable errors",
        "max attempts",
        "backoff formula",
        "jitter",
        "retry budget",
        "Circuit breakers: open/half-open/closed state machine",
        "threshold",
        "fallback",
        "Bulkheads: thread-pool / connection-pool isolation",
        "resource compartmentalization",
        "Timeouts and deadlines: connect vs. read vs. overall",
        "propagation across service calls",
        "Idempotency keys: placement",
        "scope",
        "storage",
        "expiry",
        "conflict behavior",
        "Dead-letter queues: DLQ routing",
        "poison-message detection",
        "requeue policy",
        "React 19 error boundaries: placement rules",
        "fallback UI",
        "error.tsx in Next.js App Router",
        "Framework error filters: NestJS exception filters",
        "Hono error middleware",
        "Next.js error.tsx",
        "Structured error logging: required fields",
        "log-level decision rules",
        "what to redact",
        "User-facing error messaging: public message vs. private diagnostic split",
        "Fail-loud vs. fail-silent: the decision rule for when silent degradation is acceptable",
      ],
      outOfScope: ["out-of-discipline decisions"],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "growth-distribution",
      title: "Growth Distribution",
      purpose:
        "Use this skill when a solo founder needs to select, test, measure or repair distribution channels for a web, mobile, SaaS or AI product.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "growth",
          "channel",
          "acquisition",
          "distribution",
          "viral",
          "referral",
          "paid ads",
          "plg",
          "growth loop",
          "cac",
          "payback period",
          "channel testing",
        ],
        auto: true,
      },
      owns: [
        "channel selection decisions",
        "acquisition channel testing decisions",
        "distribution strategy decisions",
        "viral/referral mechanics decisions",
        "paid/organic channel mix decisions",
        "growth model decisions",
      ],
      outOfScope: [
        "SEO/content organic growth",
        "brand/PR/narrative",
        "sales pipeline",
        "activation/onboarding",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "idea-sourcing",
      title: "Idea Sourcing and Opportunity Discovery",
      purpose:
        "Idea sourcing and opportunity discovery for solo founders. Find, filter, and pipeline startup/product ideas before committing to validation. AUTO-INVOQUER when: 'find an idea', 'idea generation', 'looking for ideas', 'what should I build',",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "find an idea",
          "idea generation",
          "looking for ideas",
          "what should i build",
          "opportunity discovery",
          "no idea yet",
          "brainstorm startup ideas",
          "find a problem to solve",
          "idea pipeline",
          "idea sourcing",
          "where do good ideas come from",
          "explore opportunities",
          "looking for opportunities",
          "explore startup ideas",
          "i don",
        ],
        auto: true,
      },
      owns: [
        "problem identification decisions",
        "trend scanning decisions",
        "ICP pain-mining decisions",
        "idea pre-filtering decisions",
        "idea pipeline decisions",
        "personal-advantage mapping decisions",
      ],
      outOfScope: [
        "PMF scoring and validation",
        "product strategy after idea is chosen",
        "positioning and messaging",
        "customer discovery interviews",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "idea-to-pmf",
      title: "Idea-to-PMF",
      purpose:
        "Research-backed idea-to-product-market-fit workflow for solo developers. Use when Codex needs to assess a startup/product idea, design customer discovery, grade PMF evidence, choose MVP scope, test willingness-to-pay, plan validation experi",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "pmf",
          "idea validation",
          "customer discovery",
          "mvp",
          "willingness to pay",
          "pivot or kill",
          "startup idea",
          "market validation",
          "early traction",
          "product-market fit",
        ],
        auto: true,
      },
      owns: [
        "idea validation decisions",
        "customer discovery decisions",
        "PMF evidence decisions",
        "MVP scope decisions",
        "willingness-to-pay decisions",
        "build/pivot/kill decisions",
        "early PMF metric decisions",
      ],
      outOfScope: [
        "product strategy after PMF",
        "positioning/messaging",
        "growth channels",
        "business strategy",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "integration-automation",
      title: "Skill: Integration and Automation",
      purpose:
        "at-least-once, exactly-once semantics); idempotency key strategies; retry budget design, exponential",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "webhook",
          "webhook delivery",
          "webhook signature",
          "hmac verify",
          "idempotency",
          "retry",
          "dead letter queue",
          "event-driven",
          "outbox pattern",
          "zapier",
          "temporal",
          "contract test",
          "sandbox testing",
          "polling vs webhook",
          "cloudevents",
        ],
        auto: true,
      },
      owns: ["Skill: Integration and Automation decisions"],
      outOfScope: ["out-of-discipline decisions"],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "metrics-analytics-data",
      title: "Metrics Analytics Data",
      purpose:
        "Use this skill when a solo founder needs decision-grade measurement: event taxonomy, metric definitions, funnels, cohorts, experimentation metrics, dashboards, data quality checks, privacy-aware analytics and AI eval dataset readiness.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "analytics",
          "event tracking",
          "metric definition",
          "dashboard",
          "funnel",
          "a/b test data",
          "data quality",
          "north star metric",
          "instrumentation",
          "attribution",
          "event taxonomy",
        ],
        auto: true,
      },
      owns: [
        "event taxonomy decisions",
        "analytics instrumentation decisions",
        "dashboard design decisions",
        "metric definition decisions",
        "experiment data decisions",
        "data quality decisions",
        "product analytics decisions",
      ],
      outOfScope: [
        "financial/SaaS metrics",
        "growth channel attribution",
        "AI/ML model metrics",
        "production monitoring/SLO",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "observability",
      title: "Skill: Observability",
      purpose:
        "PII/PCI/HIPAA/GDPR redaction; distributed tracing with OpenTelemetry and W3C Trace Context;",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "what should i log",
          "structured logging",
          "add a trace",
          "opentelemetry",
          "what metrics should i expose",
          "sli",
          "burn rate alert",
          "rum",
          "correlation id",
          "pii in logs",
          "sampling",
          "dashboard design",
          "telemetry cost",
        ],
        auto: true,
      },
      owns: ["Skill: Observability decisions"],
      outOfScope: ["out-of-discipline decisions"],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "performance-engineering",
      title: "Skill: Performance Engineering",
      purpose: "React/Next.js perf patterns)",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "the app is slow",
          "page load is bad",
          "this query is slow",
          "memory leak",
          "bundle is huge",
          "perf regression",
          "profile this",
          "cache invalidation",
          "core web vitals",
          "performance budget",
          "render thrash",
          "use method",
        ],
        auto: true,
      },
      owns: ["Skill: Performance Engineering decisions"],
      outOfScope: ["out-of-discipline decisions"],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "positioning-messaging-category",
      title: "Positioning Messaging Category",
      purpose:
        "Use this skill when a founder needs to decide how a product should be understood before writing copy, building a landing page, launching SEO/ASO, selling, pricing or repositioning.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "positioning",
          "messaging",
          "category design",
          "icp",
          "alternatives",
          "differentiation",
          "value proposition",
          "gtm",
          "who is this for",
          "why us",
          "market category",
        ],
        auto: true,
      },
      owns: [
        "category framing decisions",
        "ICP disqualification decisions",
        "competitive alternatives decisions",
        "differentiator decisions",
        "message hierarchy decisions",
        "proof claim decisions",
        "GTM positioning handoff decisions",
      ],
      outOfScope: [
        "brand voice/narrative/PR",
        "SEO keyword strategy",
        "sales discovery scripts",
        "product vision/bet selection",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "product-goal-sprint-alignment",
      title: "Skill: Product Goal Sprint Alignment",
      purpose: "Pull these from their owner books before writing a single line:",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "sprint audit",
          "aligned?",
          "is this on roadmap?",
          "product constitution",
          "icp gate",
          "escalate or continue?",
          "does this serve the icp?",
          "north star check",
          "scope creep",
          "agent governance",
          "can the agent decide this?",
          "pivot signal",
        ],
        auto: true,
      },
      owns: [
        "Product Constitution authoring",
        "sprint alignment auditing",
        "ICP coherence gating",
        "scope guard",
        "product decision governance",
        "pivot detection",
      ],
      outOfScope: [
        "Writing the original vision ()",
        "brand voice creation ()",
        "sprint process management and agent delivery orchestration ()",
        "feature spec writing ()",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "product-strategy",
      title: "Product Strategy",
      purpose:
        "Use this skill when a solo founder needs to turn validated opportunities into a product strategy, roadmap, bet portfolio, product principles or strategy review.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "product strategy",
          "roadmap",
          "product vision",
          "bet",
          "prioritization",
          "product review",
          "kill condition",
          "product principles",
          "now-next-later",
          "product portfolio",
        ],
        auto: true,
      },
      owns: [
        "product vision decisions",
        "bet portfolio decisions",
        "roadmap prioritization decisions",
        "product principle decisions",
        "product review decisions",
        "kill condition decisions",
      ],
      outOfScope: [
        "business strategy/transformation",
        "PMF validation",
        "sprint alignment/ICP gate",
        "feature specs",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "production-reliability-devops",
      title: "Production Reliability DevOps",
      purpose: "Pause and require explicit human decision before proceeding when:",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "incident",
          "on-call",
          "observability",
          "deploy",
          "reliability",
          "downtime",
          "error budget",
          "postmortem",
          "ci/cd",
          "dora metrics",
        ],
        auto: true,
      },
      owns: [
        "SLI/SLO/error budget decisions",
        "incident management decisions",
        "observability decisions",
        "CI/CD pipeline decisions",
        "deployment risk decisions",
        "on-call decisions",
        "reliability investment decisions",
      ],
      outOfScope: [
        "cloud infrastructure/IaC",
        "secure SDLC",
        "database performance",
        "code quality",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "quality-engineering",
      title: "Quality Engineering",
      purpose:
        "Use this skill when deciding or implementing testing, QA, CI gates, release readiness, defect triage, flaky test handling, non-functional quality checks, or AI/LLM evals for web, mobile, SaaS, API, data, or AI features.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "test",
          "quality gate",
          "release confidence",
          "flaky",
          "coverage",
          "ci",
          "can we ship",
          "regression",
          "shift-left",
          "qa",
          "test strategy",
        ],
        auto: true,
      },
      owns: [
        "test strategy decisions",
        "release gate decisions",
        "flaky test decisions",
        "test coverage decisions",
        "shift-left quality decisions",
        "CI quality gate decisions",
        "release confidence decisions",
      ],
      outOfScope: [
        "code maintainability",
        "security testing",
        "authorized pentest",
        "production SLO",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "schema-driven-development",
      title: "Skill: Schema-Driven Development (schema-first / contract-first)",
      purpose:
        "Thrift, OpenAPI Specification, GraphQL SDL, TypeSpec, Cap'n Proto -- selection decision tree",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: ["schema-first", "schema first approach", "should i be schema-first?"],
        auto: true,
      },
      owns: [
        "Schema-first vs. code-first decision: when each",
        "trade-offs",
        "migration path from code-first",
        "Schema language selection: JSON Schema",
        "Zod / Valibot / ArkType",
        "Protocol Buffers",
        "Avro",
        "Codegen pipelines: schema -> types / clients / server stubs / validators / docs / DB",
        "Schema evolution and compatibility: backward / forward / full compatibility rules",
        "safe",
        'Validation at the boundary: "parse',
        "don't validate\" (Alexis King 2019)",
        "validate at the",
        "Single source of truth for types across frontend / backend / DB / docs",
        "preventing",
        "File and config format design and versioning (JSON, YAML, TOML, env files)",
        "Message and event schema design (event envelopes, schema versioning in headers)",
        "Schema registries and governance: Confluent Schema Registry",
        "Buf Schema Registry",
        "BSR",
        "DRY-across-the-stack discipline: one schema",
        "zero hand-written type duplication",
        "Schema-driven anti-patterns: code-first drift",
        "hand-rolled validators at every layer",
      ],
      outOfScope: ["out-of-discipline decisions"],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "seo-content-organic-growth",
      title: "SEO Content Organic Growth",
      purpose:
        "Research-backed SEO/content organic growth operating system for solo founders building web, mobile, SaaS and AI products.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "seo",
          "content brief",
          "keyword",
          "search intent",
          "organic",
          "topic cluster",
          "internal linking",
          "schema markup",
          "crawl",
        ],
        auto: true,
      },
      owns: [
        "search intent decisions",
        "technical SEO decisions",
        "content brief decisions",
        "topic cluster decisions",
        "internal linking decisions",
        "schema markup decisions",
        "qualified organic measurement decisions",
      ],
      outOfScope: [
        "brand/PR/narrative",
        "paid acquisition channels",
        "positioning/ICP",
        "lifecycle/activation copy",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "software-delivery-governance",
      title: "Skill: Software Delivery Governance",
      purpose:
        "Choose exactly one delivery mode from `DECISION-TREES.md` Tree 1: sprint, Kanban flow, Shape Up appetite, incident response or discovery spike.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "run the sprint",
          "govern the agents",
          "software delivery governance",
          "moa moe",
          "scrum master for codex",
          "sprint planning",
          "standup blockers",
          "delivery gate",
          "can we merge",
          "sprint review evidence",
          "retro and next sprint",
          "150 sprint loop",
        ],
        auto: true,
      },
      owns: [
        "software delivery governance decisions",
        "MOA/MOE role and decision-rights decisions",
        "sprint intake/readiness decisions",
        "agent execution control decisions",
        "delivery evidence gate decisions",
        "release/change-control routing decisions",
        "retrospective improvement decisions",
      ],
      outOfScope: [
        "product vision or ICP decisions -> and",
        "feature requirement semantics ->",
        "architecture approval ->",
        "test adequacy ->",
        "code maintainability judgment ->",
        "production incident/SLO ownership ->",
        "non-software SOP/change adoption ->",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "spec-driven-development",
      title: "Skill: Spec-Driven Development",
      purpose:
        "(feature / fix / improvement / refactor); the spec -> plan -> tasks -> implement -> verify",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "write a spec for this change",
          "spec this out",
          "i need a spec before we build",
        ],
        auto: true,
      },
      owns: ["spec-first vs. code-first decision by change type", "spec granularity thresholds"],
      outOfScope: ["| Topic | Routes to |"],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "specification-requirements",
      title: "Specification Requirements",
      purpose:
        "Use this skill when a product intent, feature request, PRD, ticket, AI feature idea or implementation handoff needs to become buildable and testable.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "spec",
          "prd",
          "requirements",
          "acceptance criteria",
          "feature spec",
          "scope",
          "user story",
          "definition of done",
          "buildable",
          "implementation handoff",
          "ticket",
        ],
        auto: true,
      },
      owns: [
        "product intent formalization decisions",
        "PRD/spec decisions",
        "acceptance criteria decisions",
        "feature scope decisions",
        "AI feature spec decisions",
        "implementation handoff decisions",
      ],
      outOfScope: [
        "product strategy/bet selection",
        "UX flows/research",
        "technical feasibility",
        "sprint governance",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "technical-analysis-discovery",
      title: "Technical Analysis Discovery",
      purpose:
        "Use this skill when a coding task needs pre-implementation discovery: current-state comparison, codebase mapping, impact analysis, dependency/API evaluation, feasibility spike design, migration readiness, or analysis-to-plan handoff.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "impact analysis",
          "codebase mapping",
          "feasibility",
          "spike",
          "dependency evaluation",
          "migration readiness",
          "discovery",
          "pre-implementation",
          "technical analysis",
          "blast radius",
        ],
        auto: true,
      },
      owns: [
        "current-state comparative analysis decisions",
        "codebase mapping decisions",
        "impact analysis decisions",
        "dependency/API evaluation decisions",
        "feasibility spike decisions",
        "migration readiness decisions",
        "analysis-to-plan handoff decisions",
      ],
      outOfScope: [
        "system architecture decisions",
        "feature spec",
        "build/buy/integrate",
        "sprint planning",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "ui-knowledge",
      title: "UI/UX",
      purpose:
        "Use this skill as the compact execution surface for the UI knowledge excellence book.",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "ux",
          "landing page",
          "interface polish",
          "accessibility",
          "responsive design",
          "design system",
          "visual hierarchy",
          "component behavior",
          "conversion page",
          "typography",
          "color",
          "motion",
          "forms",
          "navigation",
          "frontend presentation quality",
        ],
        auto: true,
      },
      owns: ["UI/UX decisions"],
      outOfScope: ["out-of-discipline decisions"],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "ux-research-product-experience",
      title: "UX Research and Product Experience",
      purpose:
        "Research-backed UX research and product experience workflow for web, mobile, SaaS, marketplaces, dashboards, forms, settings, support-heavy products, and AI products. Use when Codex needs to plan or audit user research, usability tests, rec",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: ["user intent"],
        auto: true,
      },
      owns: [
        "UX research decisions",
        "product-experience decisions",
        "usability test decisions",
        "task-flow decisions",
        "onboarding and activation UX decisions",
        "product-state decisions",
        "accessibility-as-experience decisions",
        "AI trust/control UX decisions",
        "UX metric decisions",
        "support-feedback synthesis decisions",
      ],
      outOfScope: [
        "visual UI craft and component styling -> local",
        "PMF and customer discovery before product concept ->",
        "implementation architecture ->",
        "test automation/release gates ->",
      ],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
    {
      id: "web-mobile-platform",
      title: "Web Mobile Platform",
      purpose: "Invoke this skill when:",
      activation: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["session_start", "user_prompt"],
        riskClasses: ALL_RISKS,
        operatingModes: ALL_MODES,
        keywords: [
          "app store",
          "google play",
          "mobile release",
          "pwa",
          "platform api",
          "store compliance",
          "deep link",
          "push notifications",
          "mobile ci",
          "web platform",
          "app store review",
        ],
        auto: true,
      },
      owns: [
        "app store delivery decisions",
        "platform-specific API decisions",
        "mobile release decisions",
        "web platform decisions",
        "PWA decisions",
        "store compliance decisions",
        "platform capability decisions",
      ],
      outOfScope: ["cloud/infrastructure", "mobile UX flows", "production reliability", "security"],
      evidenceProduced: [],
      hookRefs: [],
      subagentRefs: [],
    },
  ],
  hooks: [
    {
      id: "risk-classification",
      title: "Risk Classification",
      purpose:
        "Canonical risk taxonomy, rank ordering, forcing signals, and operating mode mapping.",
      macroCycles: ALL_CYCLES,
      gateTypes: ["session_start", "user_prompt", "pre_tool"],
      riskClasses: ALL_RISKS,
      operatingModes: ALL_MODES,
      evidenceKeys: ["confidence_level", "risk_remaining"],
      skillRefs: ["hima-enter", "classify-risk"],
      subagentRefs: [],
    },
    {
      id: "state-machine",
      title: "State Machine",
      purpose: "Canonical macro-cycle route, state status, and guarded phase progression.",
      macroCycles: ALL_CYCLES,
      gateTypes: ["session_start", "post_tool", "stop"],
      riskClasses: ALL_RISKS,
      operatingModes: ALL_MODES,
      evidenceKeys: ["hook_decision", "known_gap"],
      skillRefs: ["hima-enter", "propose-change", "transition-phase", "status"],
      subagentRefs: ["evidence-collector"],
    },
    {
      id: "gate-policy",
      title: "Gate Policy",
      purpose: "Lifecycle gate enforcement, violation classes, and stop conditions.",
      macroCycles: ALL_CYCLES,
      gateTypes: ALL_GATES,
      riskClasses: ALL_RISKS,
      operatingModes: ALL_MODES,
      evidenceKeys: ["hook_decision", "human_validation", "explicit_human_signature"],
      skillRefs: ["hima-enter", "propose-change", "gate-policy", "close-run"],
      subagentRefs: ["evidence-collector", "reviewer"],
    },
    {
      id: "runtime-bindings",
      title: "Runtime Bindings",
      purpose:
        "Portable mapping from platform hook capabilities to canonical GateType enforcement.",
      macroCycles: ALL_CYCLES,
      gateTypes: ["session_start", "user_prompt", "pre_tool", "stop"],
      riskClasses: ALL_RISKS,
      operatingModes: ALL_MODES,
      evidenceKeys: ["hook_decision", "known_gap"],
      skillRefs: ["hima-enter", "gate-policy", "bind-runtime"],
      subagentRefs: [],
    },
    {
      id: "platform-adapters",
      title: "Platform Adapters",
      purpose: "Runtime portability expectations for Claude, Codex, and Hermes surfaces.",
      macroCycles: ALL_CYCLES,
      gateTypes: ALL_GATES,
      riskClasses: ALL_RISKS,
      operatingModes: ALL_MODES,
      evidenceKeys: ["hook_decision", "subagent_output"],
      skillRefs: ["gate-policy", "bind-runtime"],
      subagentRefs: ["reviewer", "test-writer", "evidence-collector"],
    },
    {
      id: "convergence",
      title: "Convergence",
      purpose: "Iteration control, review loops, test loops, and transition readiness.",
      macroCycles: ["build", "validation", "release", "run", "learning"],
      gateTypes: ["post_tool", "stop"],
      riskClasses: ["L", "M", "H", "C"],
      operatingModes: ALL_MODES,
      evidenceKeys: ["integration_tests", "review_1", "review_2_or_antagonist", "load_tests"],
      skillRefs: ["transition-phase", "build-inner-loop", "run-monitor"],
      subagentRefs: ["reviewer", "test-writer", "perf-profiler", "retro-facilitator"],
    },
    {
      id: "close-finalization",
      title: "Close And Finalization",
      purpose:
        "Final-state selection, known gaps, residual risk, and non-fabricated completion evidence.",
      macroCycles: ALL_CYCLES,
      gateTypes: ["stop"],
      riskClasses: ALL_RISKS,
      operatingModes: ALL_MODES,
      evidenceKeys: ["confidence_level", "known_gap", "risk_remaining"],
      skillRefs: ["transition-phase", "validate-evidence", "close-run"],
      subagentRefs: ["evidence-collector", "retro-facilitator"],
    },
    {
      id: "evidence-management",
      title: "Evidence Management",
      purpose:
        "Accepted evidence keys, subagent output capture, gap reporting, and sufficiency checks.",
      macroCycles: ALL_CYCLES,
      gateTypes: ["post_tool", "stop", "subagent_stop"],
      riskClasses: ALL_RISKS,
      operatingModes: ALL_MODES,
      evidenceKeys: [
        "ci_green",
        "sast_clean",
        "secrets_clean",
        "integration_tests",
        "subagent_output",
        "command_output",
        "files_modified",
        "known_gap",
      ],
      skillRefs: ["build-inner-loop", "validate-evidence", "run-monitor", "close-run"],
      subagentRefs: [
        "reviewer",
        "threat-modeler",
        "test-writer",
        "evidence-collector",
        "security-auditor",
        "accessibility-checker",
        "perf-profiler",
        "doc-generator",
        "retro-facilitator",
      ],
    },
  ],
  subagents: [
    {
      id: "reviewer",
      title: "Reviewer",
      purpose:
        "Perform antagonistic code review and return an approved or changes-required verdict.",
      spawn: {
        macroCycles: ["build", "validation"],
        gateTypes: ["subagent_start", "subagent_stop"],
        minimumRiskClass: "M",
        applicabilityByRisk: {
          T: "skipped",
          L: "optional",
          M: "mandatory",
          H: "mandatory",
          C: "mandatory",
        },
        operatingModes: GOVERNED_MODES,
      },
      evidenceProduced: ["review_1", "review_2_or_antagonist", "subagent_output"],
      hookRefs: ["gate-policy", "convergence", "evidence-management"],
      skillRefs: ["build-inner-loop", "validate-evidence"],
      maxParallelSafe: 3,
    },
    {
      id: "threat-modeler",
      title: "Threat Modeler",
      purpose: "Analyze new data flows with STRIDE and return residual risks and controls.",
      spawn: {
        macroCycles: ["conception"],
        gateTypes: ["subagent_start", "subagent_stop"],
        minimumRiskClass: "H",
        applicabilityByRisk: {
          T: "skipped",
          L: "skipped",
          M: "skipped",
          H: "mandatory",
          C: "mandatory",
        },
        operatingModes: GOVERNED_MODES,
      },
      evidenceProduced: ["threat_model_stride", "subagent_output", "risk_remaining"],
      hookRefs: ["evidence-management"],
      skillRefs: ["validate-evidence"],
      maxParallelSafe: 3,
    },
    {
      id: "test-writer",
      title: "Test Writer",
      purpose: "Write RED-phase tests from acceptance criteria before production implementation.",
      spawn: {
        macroCycles: ["build"],
        gateTypes: ["subagent_start", "subagent_stop"],
        minimumRiskClass: "L",
        applicabilityByRisk: {
          T: "skipped",
          L: "optional",
          M: "mandatory",
          H: "mandatory",
          C: "mandatory",
        },
        operatingModes: ALL_MODES,
      },
      evidenceProduced: ["integration_tests", "subagent_output", "command_output"],
      hookRefs: ["platform-adapters", "convergence", "evidence-management"],
      skillRefs: ["build-inner-loop"],
      maxParallelSafe: 1,
    },
    {
      id: "evidence-collector",
      title: "Evidence Collector",
      purpose: "Collect accepted evidence and recommend final state or blocking gaps.",
      spawn: {
        macroCycles: ALL_CYCLES,
        gateTypes: ["stop", "subagent_stop"],
        minimumRiskClass: "T",
        applicabilityByRisk: {
          T: "mandatory",
          L: "mandatory",
          M: "mandatory",
          H: "mandatory",
          C: "mandatory",
        },
        operatingModes: ALL_MODES,
      },
      evidenceProduced: ["subagent_output", "known_gap", "confidence_level", "risk_remaining"],
      hookRefs: [
        "state-machine",
        "gate-policy",
        "platform-adapters",
        "evidence-management",
        "close-finalization",
      ],
      skillRefs: ["transition-phase", "gate-policy", "validate-evidence", "close-run"],
      maxParallelSafe: 1,
    },
    {
      id: "security-auditor",
      title: "Security Auditor",
      purpose: "Run extended security review for H-risk increments.",
      spawn: {
        macroCycles: ["validation"],
        gateTypes: ["subagent_start", "subagent_stop"],
        minimumRiskClass: "H",
        applicabilityByRisk: {
          T: "skipped",
          L: "skipped",
          M: "optional",
          H: "mandatory",
          C: "mandatory",
        },
        operatingModes: GOVERNED_MODES,
      },
      evidenceProduced: ["dast_report", "independent_security_audit", "subagent_output"],
      hookRefs: ["evidence-management"],
      skillRefs: ["validate-evidence"],
      maxParallelSafe: 3,
    },
    {
      id: "accessibility-checker",
      title: "Accessibility Checker",
      purpose: "Check critical UI paths against accessibility requirements.",
      spawn: {
        macroCycles: ["validation"],
        gateTypes: ["subagent_start", "subagent_stop"],
        minimumRiskClass: "M",
        applicabilityByRisk: {
          T: "skipped",
          L: "skipped",
          M: "mandatory",
          H: "mandatory",
          C: "mandatory",
        },
        operatingModes: GOVERNED_MODES,
      },
      evidenceProduced: ["product_validation", "subagent_output", "known_gap"],
      hookRefs: ["evidence-management"],
      skillRefs: ["validate-evidence"],
      maxParallelSafe: 3,
    },
    {
      id: "perf-profiler",
      title: "Performance Profiler",
      purpose: "Measure latency, throughput, and error rates against SLOs.",
      spawn: {
        macroCycles: ["validation", "run"],
        gateTypes: ["subagent_start", "subagent_stop"],
        minimumRiskClass: "M",
        applicabilityByRisk: {
          T: "skipped",
          L: "skipped",
          M: "optional",
          H: "mandatory",
          C: "mandatory",
        },
        operatingModes: GOVERNED_MODES,
      },
      evidenceProduced: ["load_tests", "command_output", "subagent_output"],
      hookRefs: ["convergence", "evidence-management"],
      skillRefs: ["run-monitor"],
      maxParallelSafe: 3,
    },
    {
      id: "doc-generator",
      title: "Doc Generator",
      purpose: "Prepare user-facing documentation deltas from behavior changes.",
      spawn: {
        macroCycles: ["build", "release", "learning"],
        gateTypes: ["subagent_start", "subagent_stop"],
        minimumRiskClass: "L",
        applicabilityByRisk: {
          T: "skipped",
          L: "optional",
          M: "optional",
          H: "mandatory",
          C: "mandatory",
        },
        operatingModes: ALL_MODES,
      },
      evidenceProduced: ["files_modified", "subagent_output"],
      hookRefs: ["evidence-management"],
      skillRefs: ["validate-evidence"],
      maxParallelSafe: 3,
    },
    {
      id: "retro-facilitator",
      title: "Retro Facilitator",
      purpose: "Summarize learning-cycle outcomes and produce action items.",
      spawn: {
        macroCycles: ["learning"],
        gateTypes: ["subagent_start", "subagent_stop"],
        minimumRiskClass: "M",
        applicabilityByRisk: {
          T: "skipped",
          L: "skipped",
          M: "mandatory",
          H: "mandatory",
          C: "mandatory",
        },
        operatingModes: GOVERNED_MODES,
      },
      evidenceProduced: ["product_validation", "subagent_output", "known_gap"],
      hookRefs: ["convergence", "close-finalization", "evidence-management"],
      skillRefs: ["validate-evidence"],
      maxParallelSafe: 1,
    },
  ],
} as const satisfies OperationalCatalog;

export function getSkillsCatalog(): SkillCatalogEntry[] {
  return [...OPERATIONAL_CATALOG.skills];
}

export function getHooksCatalog(): HookCatalogEntry[] {
  return [...OPERATIONAL_CATALOG.hooks];
}

export function getSubagentsCatalog(): SubagentCatalogEntry[] {
  return [...OPERATIONAL_CATALOG.subagents];
}

export function getOperationalCatalog(): OperationalCatalog {
  return {
    skills: getSkillsCatalog(),
    hooks: getHooksCatalog(),
    subagents: getSubagentsCatalog(),
  };
}
