/**
 * BEH-023 — Three-State Completion Status
 *
 * Reads the completionStatus field on EvidenceRecord items in the Evidence Set
 * at the stop gate. Emits a warn or block depending on risk class when any
 * mandatory evidence record carries DONE_UNTESTED or ATTEMPTED_UNCONFIRMED.
 *
 * Classifier method: evidence_state
 * Enforcing gate: stop
 *
 * Three-value vocabulary (from canonical.ts COMPLETION_STATUSES):
 *   DONE_VERIFIED        — implemented and verified by a test or observation
 *   DONE_UNTESTED        — implemented but tests not run or not green
 *   ATTEMPTED_UNCONFIRMED — action attempted but outcome not confirmed
 *
 * Risk-floor policy (from spec BEH-023):
 *   T/L  → warn, allow DONE_WITH_GAPS
 *   M    → warn, require explicit acknowledgement or upgrade
 *   H/C  → block, require upgrade to DONE_VERIFIED
 *
 * Integration points (do NOT edit this file to wire):
 *   evaluate-gate.ts stop handler must call evaluateBehaviors(context, event)
 *   after its existing evidence checks so BEH-023 runs as part of the stop gate.
 *   EvidenceRecord.completionStatus is already present in the run-set schema
 *   (run-set.schema.ts EvidenceItemSchema.completionStatus).
 *
 * Spec: docs/conception/12-behaviors-catalog-spec.md §6 BEH-023
 */

import type { BehaviorDescriptor, BehaviorVerdict } from "../gates/behavior-registry.js";
import type { GateEvaluationContext } from "../gates/evaluate-gate.js";
import type { GateEvent } from "../schemas/gate-event.schema.js";
import type { CompletionStatus } from "../schemas/run-set.schema.js";
import { riskAtLeast } from "../types/canonical.js";

// ── Constants ─────────────────────────────────────────────────────────────────

/** Completion statuses that are not fully verified. */
export const INCOMPLETE_STATUSES: readonly CompletionStatus[] = [
  "DONE_UNTESTED",
  "ATTEMPTED_UNCONFIRMED",
] as const;

// ── Helper: scan evidence for incomplete status ───────────────────────────────

export interface IncompleteEvidenceResult {
  /** Evidence record IDs that carry an incomplete completionStatus. */
  readonly incompleteIds: readonly string[];
  /** The worst incompleteness found: ATTEMPTED_UNCONFIRMED > DONE_UNTESTED. */
  readonly worstStatus: CompletionStatus | null;
}

/**
 * Scans all EvidenceRecord items in the run-set Evidence Set for items whose
 * completionStatus is DONE_UNTESTED or ATTEMPTED_UNCONFIRMED.
 *
 * Records without a completionStatus field are treated as DONE_VERIFIED for
 * backwards-compatibility (the field is optional in the schema).
 */
export function findIncompleteEvidenceRecords(
  context: GateEvaluationContext,
): IncompleteEvidenceResult {
  const evidence = context.runSet.evidence ?? [];

  const incompleteIds: string[] = [];
  let worstStatus: CompletionStatus | null = null;

  for (const item of evidence) {
    const status = item.completionStatus as CompletionStatus | undefined;
    if (!status) continue; // treat absent as DONE_VERIFIED (backwards compat)

    if ((INCOMPLETE_STATUSES as readonly string[]).includes(status)) {
      incompleteIds.push(item.id);

      // ATTEMPTED_UNCONFIRMED is worse than DONE_UNTESTED
      if (
        worstStatus === null ||
        (status === "ATTEMPTED_UNCONFIRMED" && worstStatus === "DONE_UNTESTED")
      ) {
        worstStatus = status;
      }
    }
  }

  return { incompleteIds, worstStatus };
}

// ── BEH-023 descriptor ────────────────────────────────────────────────────────

export const beh023CompletionStatus: BehaviorDescriptor = {
  id: "BEH-023",
  name: "Three-State Completion Status",
  gates: ["stop"],

  classify(context: GateEvaluationContext, _event: GateEvent): BehaviorVerdict {
    const riskClass = context.currentRisk.risk_class;
    const { incompleteIds, worstStatus } = findIncompleteEvidenceRecords(context);

    if (incompleteIds.length === 0 || worstStatus === null) {
      return null; // All evidence is DONE_VERIFIED or unmarked — abstain
    }

    const idList = incompleteIds.join(", ");
    const statusLabel = worstStatus;

    // H/C: block — DONE_VERIFIED required
    if (riskAtLeast(riskClass, "H")) {
      return {
        decision: "block",
        reason:
          `BEH-023: ${incompleteIds.length} evidence record(s) carry incompleteness ` +
          `status "${statusLabel}" at risk class ${riskClass}. ` +
          "All mandatory evidence must be upgraded to DONE_VERIFIED before DONE_VERIFIED " +
          `can be reached. Affected record IDs: ${idList}.`,
        violationType: "DONE_WITHOUT_EVIDENCE",
        qualityDimension: "evidence",
        finalState: "BLOCKED_POLICY",
      };
    }

    // M: warn — require acknowledgement or upgrade
    if (riskAtLeast(riskClass, "M")) {
      return {
        decision: "warn",
        reason:
          `BEH-023: ${incompleteIds.length} evidence record(s) carry incompleteness ` +
          `status "${statusLabel}" at risk class ${riskClass}. ` +
          "Upgrade to DONE_VERIFIED or explicitly acknowledge before promotion. " +
          `Affected record IDs: ${idList}.`,
        qualityDimension: "evidence",
        finalState: "DONE_WITH_GAPS",
      };
    }

    // T/L: warn — allow DONE_WITH_GAPS
    return {
      decision: "warn",
      reason:
        `BEH-023: ${incompleteIds.length} evidence record(s) carry incompleteness ` +
        `status "${statusLabel}" at risk class ${riskClass}. ` +
        `Outcome will be DONE_WITH_GAPS. Affected record IDs: ${idList}.`,
      qualityDimension: "evidence",
      finalState: "DONE_WITH_GAPS",
    };
  },
};

// Registration is handled explicitly in behaviors/index.ts (M1 fix: unified pattern).
