/**
 * BEH-020 — Critic Gate: Reviewer Required Before Verify-to-Capitalize Transition
 *
 * Enforces that a reviewer subagent result exists in the Evidence Set before
 * the build/Verify → build/Capitalize transition is allowed for runs at risk
 * class M and above.
 *
 * Classifier method: evidence_state
 * Enforcing gate: subagent_stop
 *
 * Integration point (do NOT edit this file to wire):
 *   transition-policy.ts must call evaluateBehaviors(context, event) at the
 *   subagent_stop gate when transitioning from build/Verify to build/Capitalize,
 *   and treat a "block" verdict as a transition guard failure.
 *
 * Spec: docs/conception/12-behaviors-catalog-spec.md §6 BEH-020
 */

import type { BehaviorDescriptor, BehaviorVerdict } from "../gates/behavior-registry.js";
import type { GateEvaluationContext } from "../gates/evaluate-gate.js";
import type { GateEvent } from "../schemas/gate-event.schema.js";
import { riskAtLeast } from "../types/canonical.js";

// ── Constants ─────────────────────────────────────────────────────────────────

/** Evidence path the reviewer subagent result must be present under. */
export const REVIEWER_EVIDENCE_PATH = "subagent_output" as const;

/** Accepted reviewer verdicts — both signal the gate was exercised. */
export const REVIEWER_ACCEPTED_VERDICTS = ["APPROVED", "CHANGES_REQUIRED"] as const;
export type ReviewerVerdict = (typeof REVIEWER_ACCEPTED_VERDICTS)[number];

// ── Helper: check reviewer evidence presence ──────────────────────────────────

/**
 * Returns true when the run-set evidence contains at least one record whose
 * key is "subagent_output" and whose metadata.role === "reviewer" with an
 * accepted verdict (APPROVED or CHANGES_REQUIRED).
 *
 * The evidence_state classifier reads run-set.json#/evidence; it does NOT
 * scan agent output text.
 */
export function hasReviewerEvidence(context: GateEvaluationContext): boolean {
  const evidence = context.runSet.evidence ?? [];

  return evidence.some((item) => {
    if (item.key !== REVIEWER_EVIDENCE_PATH) return false;

    // Check metadata for role=reviewer and a valid verdict field
    const meta = item.metadata as Record<string, unknown> | undefined;
    if (!meta) return false;
    if (meta.role !== "reviewer") return false;

    const verdict = meta.verdict as string | undefined;
    return verdict === "APPROVED" || verdict === "CHANGES_REQUIRED";
  });
}

// ── BEH-020 descriptor ────────────────────────────────────────────────────────

export const beh020CriticGate: BehaviorDescriptor = {
  id: "BEH-020",
  name: "Critic Gate — Reviewer Required Before Verify-to-Capitalize",
  gates: ["subagent_stop"],

  classify(context: GateEvaluationContext, _event: GateEvent): BehaviorVerdict {
    const riskClass = context.currentRisk.risk_class;

    // Only enforce at M and above
    if (!riskAtLeast(riskClass, "M")) {
      return null;
    }

    // Check current subPhase: only block when transitioning from Verify
    const subPhase = context.runSet.route?.subPhase;
    if (subPhase !== "Verify") {
      return null;
    }

    if (hasReviewerEvidence(context)) {
      return null;
    }

    return {
      decision: "block",
      reason:
        "BEH-020: Verify-to-Capitalize transition blocked — no reviewer subagent evidence " +
        `found in run-set.json#/evidence for risk class ${riskClass}. ` +
        "A reviewer subagent must produce an APPROVED or CHANGES_REQUIRED record " +
        "before the build/Capitalize sub-phase may begin.",
      violationType: "DONE_WITHOUT_EVIDENCE",
      qualityDimension: "review",
      finalState: undefined,
    };
  },
};

// Registration is handled explicitly in behaviors/index.ts (M1 fix: unified pattern).
