/**
 * BEH-022 — Loop Detection with LOOP_DETECTED Final State Emission
 *
 * Implements a sliding-window ring buffer of (toolName, argsHash, resultHash)
 * triples from run-set.json events. Two consecutive identical triples produce
 * a warn; three consecutive identical triples produce a block with
 * finalState: "LOOP_DETECTED".
 *
 * Classifier method: composite (tool_type + evidence_state ring buffer)
 * Enforcing gate: post_tool
 *
 * Ring buffer persistence:
 *   The buffer is read from and written to run-set.json#/loopDetector.
 *   The schema types (LoopDetector, LoopDetectorEntry) are already defined in
 *   packages/core/src/schemas/run-set.schema.ts.
 *
 * Integration points (do NOT edit this file to wire):
 *   evaluate-gate.ts post_tool handler must:
 *     1. Call appendLoopDetectorEntry(runSet, entry) after every post_tool event.
 *     2. Call evaluateBehaviors(context, event) which invokes this classifier.
 *   The ring buffer mutation (appendLoopDetectorEntry) must be persisted to
 *   .planning/run-set.json by the calling handler — this module is pure logic.
 *
 * Spec: docs/conception/12-behaviors-catalog-spec.md §6 BEH-022
 */

import { hashContent } from "../gates/action-signal.js";
import type { BehaviorDescriptor, BehaviorVerdict } from "../gates/behavior-registry.js";
import type { GateEvaluationContext } from "../gates/evaluate-gate.js";
import type { GateEvent } from "../schemas/gate-event.schema.js";
import type { LoopDetector, LoopDetectorEntry } from "../schemas/run-set.schema.js";

// ── Constants ─────────────────────────────────────────────────────────────────

/** Maximum number of entries retained in the ring buffer. */
export const LOOP_DETECTOR_MAX_ENTRIES = 10;

/** Number of consecutive identical triples that produces a warn. */
export const LOOP_WARN_THRESHOLD = 2;

/** Number of consecutive identical triples that produces a block. */
export const LOOP_BLOCK_THRESHOLD = 3;

// ── Ring buffer helpers ───────────────────────────────────────────────────────

/**
 * Stable sentinel used as argsHash / resultHash when the tool input or output
 * is absent (undefined, null, or empty string). Using a fixed non-empty token
 * preserves the LoopDetectorEntrySchema constraint (z.string().min(1)) while
 * still allowing two events with absent inputs to match each other.
 */
export const EMPTY_CONTENT_SENTINEL = "empty";

/**
 * Builds a LoopDetectorEntry from a post_tool GateEvent.
 *
 * argsHash: JSON-canonical SHA-256 of toolInput, or EMPTY_CONTENT_SENTINEL
 * resultHash: JSON-canonical SHA-256 of toolOutput, or EMPTY_CONTENT_SENTINEL
 */
export function buildLoopDetectorEntry(event: GateEvent): LoopDetectorEntry {
  const rawArgs = hashContent(event.toolInput);
  const rawResult = hashContent(event.toolOutput);
  return {
    toolName: event.toolName?.length ? event.toolName : "unknown",
    argsHash: rawArgs.length > 0 ? rawArgs : EMPTY_CONTENT_SENTINEL,
    resultHash: rawResult.length > 0 ? rawResult : EMPTY_CONTENT_SENTINEL,
    ts: new Date().toISOString(),
  };
}

/**
 * Returns true when two LoopDetectorEntry values represent the same
 * (toolName, argsHash, resultHash) triple — i.e. the same tool call
 * with the same arguments produced the same result.
 */
export function entriesMatch(a: LoopDetectorEntry, b: LoopDetectorEntry): boolean {
  return a.toolName === b.toolName && a.argsHash === b.argsHash && a.resultHash === b.resultHash;
}

/**
 * Counts how many trailing entries in the ring buffer entries array are
 * identical to the candidate entry (including the candidate itself).
 *
 * Returns 1 when only the candidate itself matches (no prior repetition),
 * 2 when the candidate and the immediately preceding entry match, etc.
 */
export function countConsecutiveTrailingMatches(
  entries: readonly LoopDetectorEntry[],
  candidate: LoopDetectorEntry,
): number {
  // entries is ordered oldest-first; we scan from the end backwards.
  let count = 0;
  for (let i = entries.length - 1; i >= 0; i--) {
    const entry = entries[i];
    if (entry !== undefined && entriesMatch(entry, candidate)) {
      count++;
    } else {
      break;
    }
  }
  // Include the candidate itself
  return count + 1;
}

/**
 * Produces a new LoopDetector state by appending the entry to the ring buffer
 * and updating consecutiveMatchCount. The buffer is capped at maxEntries.
 *
 * This is a pure function — it does not mutate the existing runSet.
 * The caller is responsible for writing the returned value to run-set.json.
 */
export function appendLoopDetectorEntry(
  current: LoopDetector | undefined,
  entry: LoopDetectorEntry,
): LoopDetector {
  const maxEntries = current?.maxEntries ?? LOOP_DETECTOR_MAX_ENTRIES;
  const existing = current?.entries ?? [];

  const consecutiveMatches = countConsecutiveTrailingMatches(existing, entry);

  // Append and trim to maxEntries (ring buffer semantics: drop oldest)
  const updated = [...existing, entry];
  const trimmed =
    updated.length > maxEntries ? updated.slice(updated.length - maxEntries) : updated;

  return {
    entries: trimmed,
    maxEntries,
    consecutiveMatchCount: consecutiveMatches,
  };
}

// ── Verdict derivation ────────────────────────────────────────────────────────

/**
 * Derives a BehaviorVerdict from a consecutive-match count.
 *
 * count < WARN_THRESHOLD  → null (abstain)
 * count === WARN_THRESHOLD → warn LOOP_WARNING
 * count >= BLOCK_THRESHOLD → block LOOP_DETECTED
 */
export function verdictFromMatchCount(count: number): BehaviorVerdict {
  if (count >= LOOP_BLOCK_THRESHOLD) {
    return {
      decision: "block",
      reason:
        `BEH-022: LOOP_DETECTED — ${count} consecutive identical ` +
        "(toolName, argsHash, resultHash) triples observed. " +
        "The agent is repeating the same tool call with identical arguments " +
        "and receiving identical results. Terminating with LOOP_DETECTED.",
      finalState: "LOOP_DETECTED",
    };
  }

  if (count >= LOOP_WARN_THRESHOLD) {
    return {
      decision: "warn",
      reason:
        `BEH-022: LOOP_WARNING — ${count} consecutive identical triples observed. ` +
        `A third identical triple will trigger LOOP_DETECTED (block).`,
    };
  }

  return null;
}

// ── BEH-022 descriptor ────────────────────────────────────────────────────────

export const beh022LoopDetector: BehaviorDescriptor = {
  id: "BEH-022",
  name: "Loop Detection — Sliding Window with LOOP_DETECTED Emission",
  gates: ["post_tool"],

  classify(context: GateEvaluationContext, event: GateEvent): BehaviorVerdict {
    // BEH-022 fires at all risk classes (risk_floor: T per spec).
    // Build the candidate entry from the current post_tool event.
    const candidate = buildLoopDetectorEntry(event);

    // Read current ring buffer from run-set.json (may be absent on first event).
    const loopDetector = context.runSet.loopDetector;
    const existingEntries = loopDetector?.entries ?? [];

    // Compute consecutive-match count against the existing buffer
    // (candidate is NOT yet in the buffer — that write is the integration's job).
    const consecutiveMatches = countConsecutiveTrailingMatches(existingEntries, candidate);

    return verdictFromMatchCount(consecutiveMatches);
  },
};

// Registration is handled explicitly in behaviors/index.ts (M1 fix: unified pattern).
