/**
 * BEH-021 — Dimension-Specific Retry and Escalation Policy
 *
 * Classifies gate violations by quality dimension (security, tests, review,
 * evidence, suppression) and enforces per-dimension retry/escalation policy
 * rather than the uniform three-attempt cap applied to all failures.
 *
 * Classifier method: evidence_state
 * Enforcing gates: stop, subagent_stop
 *
 * Integration points (do NOT edit this file to wire):
 *   1. transition-policy.ts: when emitting a gate violation, populate
 *      qualityDimension on the violation before calling evaluateBehaviors.
 *   2. baseline-policy.ts / PolicyConfig: fold DIMENSION_RETRY_POLICY entries
 *      into the policy configuration so operators may override per-dimension
 *      limits at deploy time.
 *   3. The evaluator must read the current attempt count from
 *      run-set.json#/events filtered by violation type, then compare against
 *      the dimension policy to decide whether to escalate.
 *
 * Spec: docs/conception/12-behaviors-catalog-spec.md §6 BEH-021
 */

import type { BehaviorDescriptor, BehaviorVerdict } from "../gates/behavior-registry.js";
import type { GateEvaluationContext } from "../gates/evaluate-gate.js";
import type { GateEvent } from "../schemas/gate-event.schema.js";
import type { QualityDimension } from "../types/canonical.js";
import { riskAtLeast } from "../types/canonical.js";

// ── Per-dimension policy table ────────────────────────────────────────────────

export interface DimensionRetryPolicy {
  /** Maximum number of autonomous fix attempts before escalating. */
  readonly maxAttempts: number;
  /**
   * When true, escalate to BLOCKED_NEEDS_USER on the first failure at
   * risk class H or C, bypassing the maxAttempts cap.
   */
  readonly escalateImmediately: boolean;
}

/**
 * Canonical per-dimension retry and escalation policy table.
 *
 * security:    immediate escalation at H/C — one security finding is one too many
 * tests:       three autonomous attempts before escalating
 * review:      two attempts (reviewer may be re-invoked once on CHANGES_REQUIRED)
 * evidence:    two attempts with immediate escalation at H/C
 * suppression: three attempts (suppressions are rarely blocking)
 */
export const DIMENSION_RETRY_POLICY: Readonly<Record<QualityDimension, DimensionRetryPolicy>> = {
  security: { maxAttempts: 1, escalateImmediately: true },
  tests: { maxAttempts: 3, escalateImmediately: false },
  review: { maxAttempts: 2, escalateImmediately: false },
  evidence: { maxAttempts: 2, escalateImmediately: true },
  suppression: { maxAttempts: 3, escalateImmediately: false },
} as const;

// ── Helper: count prior violation attempts for a dimension ────────────────────

/**
 * Counts how many gate violation attempts for the given qualityDimension have
 * already been recorded in run-set.json#/events.
 *
 * Fix M5: handle-hook.ts writes events with type "GATE_EVALUATED" (never
 * "gate_violation" — that type does not exist in production). The violationType
 * and qualityDimension are stored in the event payload. We count GATE_EVALUATED
 * events that:
 *   - decision === "block" or "warn" (i.e. an actual violation, not an allow)
 *   - payload.qualityDimension matches the target dimension
 *
 * This is the attempt count used to decide whether maxAttempts is exceeded.
 */
export function countPriorViolationAttempts(
  context: GateEvaluationContext,
  dimension: QualityDimension,
): number {
  const events = context.runSet.events ?? [];
  return events.filter((e) => {
    // Match the real event type that handle-hook.ts writes (GATE_EVALUATED).
    if (e.type !== "GATE_EVALUATED") return false;
    // Only count actual violations (block or warn decisions).
    if (e.decision !== "block" && e.decision !== "warn") return false;
    const payload = e.payload as Record<string, unknown> | undefined;
    return payload?.qualityDimension === dimension;
  }).length;
}

// ── BEH-021 descriptor ────────────────────────────────────────────────────────

export const beh021DimensionRetry: BehaviorDescriptor = {
  id: "BEH-021",
  name: "Dimension-Specific Retry and Escalation Policy",
  gates: ["stop", "subagent_stop"],

  classify(context: GateEvaluationContext, event: GateEvent): BehaviorVerdict {
    const riskClass = context.currentRisk.risk_class;

    // Only enforce at M and above
    if (!riskAtLeast(riskClass, "M")) {
      return null;
    }

    // BEH-021 acts as a meta-classifier: it reads the latest unresolved violation
    // dimension from the event payload if the caller attached qualityDimension.
    // This behavior fires when evaluateBehaviors is called with a gate event whose
    // metadata carries an unresolved qualityDimension needing policy adjudication.
    const meta = event.metadata as Record<string, unknown> | undefined;
    const dimension = meta?.qualityDimension as QualityDimension | undefined;

    if (!dimension || !(dimension in DIMENSION_RETRY_POLICY)) {
      // No dimension signal on this event — abstain
      return null;
    }

    const policy = DIMENSION_RETRY_POLICY[dimension];
    const priorAttempts = countPriorViolationAttempts(context, dimension);

    // Immediate-escalation dimensions at H/C: block on first occurrence
    if (policy.escalateImmediately && riskAtLeast(riskClass, "H")) {
      return {
        decision: "block",
        reason:
          `BEH-021: ${dimension} dimension violation at risk class ${riskClass} ` +
          "requires immediate escalation — maxAttempts=1, escalateImmediately=true. " +
          "This run must be reviewed by a human before retrying.",
        violationType: "UNRESOLVED_POLICY_VIOLATION",
        qualityDimension: dimension,
        finalState: "BLOCKED_NEEDS_USER",
      };
    }

    // maxAttempts cap exceeded
    if (priorAttempts >= policy.maxAttempts) {
      return {
        decision: "block",
        reason:
          `BEH-021: ${dimension} dimension violation has reached maxAttempts ` +
          `(${policy.maxAttempts}). Prior recorded attempts: ${priorAttempts}. ` +
          "Escalating to BLOCKED_NEEDS_USER — autonomous retry cap exhausted.",
        violationType: "UNRESOLVED_POLICY_VIOLATION",
        qualityDimension: dimension,
        finalState: "BLOCKED_NEEDS_USER",
      };
    }

    // Within cap and no immediate escalation — warn with attempt context
    return {
      decision: "warn",
      reason:
        `BEH-021: ${dimension} dimension violation — attempt ${priorAttempts + 1} of ` +
        `${policy.maxAttempts} allowed. Policy: escalateImmediately=${policy.escalateImmediately}.`,
      qualityDimension: dimension,
    };
  },
};

// Registration is handled explicitly in behaviors/index.ts (M1 fix: unified pattern).
