param(
  [Parameter(Mandatory = $true)]
  [string]$OsLabel,

  [Parameter(Mandatory = $true)]
  [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$CliPath = Join-Path $RepoRoot "packages/cli/dist/index.js"
$TempRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("hima-h3-install-" + $OsLabel + "-" + [System.Guid]::NewGuid().ToString("N"))
$Targets = @("claude", "codex", "hermes")
$StartedAt = (Get-Date).ToUniversalTime().ToString("o")
$Failures = New-Object System.Collections.Generic.List[string]
$env:CI = "true"

New-Item -ItemType Directory -Force -Path $TempRoot | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputPath) | Out-Null

function Add-Line {
  param([string]$Line = "")
  Add-Content -Path $OutputPath -Value $Line -Encoding UTF8
}

function Invoke-TranscriptCommand {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Title,
    [Parameter(Mandatory = $true)]
    [string[]]$Command
  )

  Add-Line ""
  Add-Line "### $Title"
  Add-Line ""
  Add-Line '```text'
  Add-Line ("> " + ($Command -join " "))

  $output = & $Command[0] @($Command | Select-Object -Skip 1) 2>&1
  $exitCode = $LASTEXITCODE

  foreach ($line in $output) {
    Add-Line ([string]$line)
  }

  Add-Line "EXIT_CODE=$exitCode"
  Add-Line '```'

  if ($exitCode -ne 0) {
    $Failures.Add("$Title exited $exitCode")
  }
}

Remove-Item -Force -ErrorAction SilentlyContinue $OutputPath

Add-Line "# H3 Install Matrix Transcript - $OsLabel"
Add-Line ""
Add-Line "This transcript is generated by the H3 transcript script. It is partial H3 evidence only; full H3 closure still requires accepted Linux, macOS, and Windows PASS transcripts."
Add-Line ""
Add-Line "## Host Identity"
Add-Line ""
Add-Line "| Field | Value |"
Add-Line "|---|---|"
Add-Line "| OS label | $OsLabel |"
Add-Line "| PowerShell | $($PSVersionTable.PSVersion) |"
Add-Line "| Platform | $([System.Runtime.InteropServices.RuntimeInformation]::OSDescription) |"
Add-Line "| Architecture | $([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture) |"
Add-Line "| Started at UTC | $StartedAt |"
Add-Line "| Temp root | $TempRoot |"
Add-Line "| Repo root | $RepoRoot |"
Add-Line ""
Add-Line "## Toolchain"

Invoke-TranscriptCommand -Title "Node version" -Command @("node", "--version")
Invoke-TranscriptCommand -Title "Corepack version" -Command @("corepack", "--version")
Invoke-TranscriptCommand -Title "pnpm version" -Command @("corepack", "pnpm", "--version")
Invoke-TranscriptCommand -Title "Git SHA" -Command @("git", "-C", $RepoRoot, "rev-parse", "HEAD")
Invoke-TranscriptCommand -Title "Git status" -Command @("git", "-C", $RepoRoot, "status", "--short")

Add-Line ""
Add-Line "## Build Precondition"
Invoke-TranscriptCommand -Title "Install dependencies" -Command @("corepack", "pnpm", "install", "--frozen-lockfile")
Invoke-TranscriptCommand -Title "Build" -Command @("corepack", "pnpm", "build")
Invoke-TranscriptCommand -Title "Initialize planning project" -Command @("node", $CliPath, "init", "--root", $TempRoot)

foreach ($target in $Targets) {
  Add-Line ""
  Add-Line "## Target: $target"

  Invoke-TranscriptCommand -Title "$target install" -Command @("node", $CliPath, "install", $target, "--root", $TempRoot, "--apply", "--writeManifest", "--json")
  Invoke-TranscriptCommand -Title "$target install artifacts" -Command @("node", $CliPath, "install-artifacts", $target, "--root", $TempRoot, "--apply", "--writeManifest", "--captureRestoreSnapshots", "--json")
  Invoke-TranscriptCommand -Title "$target lifecycle apply" -Command @("node", $CliPath, "lifecycle", "apply", $target, "--root", $TempRoot, "--apply", "--json")
  Invoke-TranscriptCommand -Title "$target runtime probe" -Command @("node", $CliPath, "runtime", "probe", $target, "--root", $TempRoot, "--bind", "--verifyBlockingFixtures", "--json")
  Invoke-TranscriptCommand -Title "$target self-test" -Command @("node", $CliPath, "self-test", "--root", $TempRoot, "--target", $target, "--json")
}

$FinishedAt = (Get-Date).ToUniversalTime().ToString("o")

Add-Line ""
Add-Line "## Verdict"
Add-Line ""
Add-Line "| Field | Value |"
Add-Line "|---|---|"
Add-Line "| Finished at UTC | $FinishedAt |"
Add-Line "| Transcript output | $OutputPath |"
Add-Line "| Failure count | $($Failures.Count) |"

if ($Failures.Count -gt 0) {
  Add-Line ""
  Add-Line "### Failures"
  foreach ($failure in $Failures) {
    Add-Line "- $failure"
  }
  exit 1
}

Add-Line ""
Add-Line "PASS: all local install-matrix commands exited 0 on $OsLabel."
