#!/usr/bin/env bash
set -uo pipefail

if [[ $# -ne 2 ]]; then
  printf 'Usage: %s <os-label> <output-path>\n' "$0" >&2
  exit 2
fi

OS_LABEL="$1"
OUTPUT_PATH="$2"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
CLI_PATH="$REPO_ROOT/packages/cli/dist/index.js"
TEMP_ROOT="${TMPDIR:-/tmp}/hima-h3-install-${OS_LABEL}-$(date +%s)-$$"
TARGETS=(claude codex hermes)
STARTED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
FAILURES=()
export CI="${CI:-true}"

mkdir -p "$TEMP_ROOT"
mkdir -p "$(dirname -- "$OUTPUT_PATH")"
rm -f "$OUTPUT_PATH"

add_line() {
  printf '%s\n' "${1:-}" >> "$OUTPUT_PATH"
}

invoke_transcript_command() {
  local title="$1"
  shift
  local output
  local exit_code

  add_line ""
  add_line "### $title"
  add_line ""
  add_line '```text'
  add_line "> $*"

  output="$("$@" 2>&1)"
  exit_code=$?
  if [[ -n "$output" ]]; then
    printf '%s\n' "$output" >> "$OUTPUT_PATH"
  fi
  add_line "EXIT_CODE=$exit_code"
  add_line '```'

  if [[ $exit_code -ne 0 ]]; then
    FAILURES+=("$title exited $exit_code")
  fi
}

add_line "# H3 Install Matrix Transcript - $OS_LABEL"
add_line ""
add_line "This transcript is generated by the H3 transcript script. It is partial H3 evidence only; full H3 closure still requires accepted Linux, macOS, and Windows PASS transcripts."
add_line ""
add_line "## Host Identity"
add_line ""
add_line "| Field | Value |"
add_line "|---|---|"
add_line "| OS label | $OS_LABEL |"
add_line "| Shell | ${SHELL:-bash} |"
add_line "| Platform | $(uname -a) |"
add_line "| Architecture | $(uname -m) |"
add_line "| Started at UTC | $STARTED_AT |"
add_line "| Temp root | $TEMP_ROOT |"
add_line "| Repo root | $REPO_ROOT |"
add_line ""
add_line "## Toolchain"

invoke_transcript_command "Node version" node --version
invoke_transcript_command "Corepack version" corepack --version
invoke_transcript_command "pnpm version" corepack pnpm --version
invoke_transcript_command "Git SHA" git -C "$REPO_ROOT" rev-parse HEAD
invoke_transcript_command "Git status" git -C "$REPO_ROOT" status --short

add_line ""
add_line "## Build Precondition"
invoke_transcript_command "Install dependencies" corepack pnpm install --frozen-lockfile
invoke_transcript_command "Build" corepack pnpm build
invoke_transcript_command "Initialize planning project" node "$CLI_PATH" init --root "$TEMP_ROOT"

for target in "${TARGETS[@]}"; do
  add_line ""
  add_line "## Target: $target"

  invoke_transcript_command "$target install" node "$CLI_PATH" install "$target" --root "$TEMP_ROOT" --apply --writeManifest --json
  invoke_transcript_command "$target install artifacts" node "$CLI_PATH" install-artifacts "$target" --root "$TEMP_ROOT" --apply --writeManifest --captureRestoreSnapshots --json
  invoke_transcript_command "$target lifecycle apply" node "$CLI_PATH" lifecycle apply "$target" --root "$TEMP_ROOT" --apply --json
  invoke_transcript_command "$target runtime probe" node "$CLI_PATH" runtime probe "$target" --root "$TEMP_ROOT" --bind --verifyBlockingFixtures --json
  invoke_transcript_command "$target self-test" node "$CLI_PATH" self-test --root "$TEMP_ROOT" --target "$target" --json
done

FINISHED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

add_line ""
add_line "## Verdict"
add_line ""
add_line "| Field | Value |"
add_line "|---|---|"
add_line "| Finished at UTC | $FINISHED_AT |"
add_line "| Transcript output | $OUTPUT_PATH |"
add_line "| Failure count | ${#FAILURES[@]} |"

if [[ ${#FAILURES[@]} -gt 0 ]]; then
  add_line ""
  add_line "### Failures"
  for failure in "${FAILURES[@]}"; do
    add_line "- $failure"
  done
  exit 1
fi

add_line ""
add_line "PASS: all local install-matrix commands exited 0 on $OS_LABEL."
