/**
 * @harness/generator — consommable -> hima catalog artifacts.
 * Pipeline: PARSE -> MAP -> VALIDATE -> EMIT(staging) -> VERIFY+canary.
 * GOAL-3 §10 Execution Contract is authoritative. Staging-only first
 * iteration (architecture decision D1): emits to src/generated/, does NOT
 * mutate operational-catalog.ts (that is Tidy-First Slice 2, later).
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { type CanaryResult, runCanary } from "./canary.js";
import {
  buildActivateSkill,
  type DraftEntry,
  mapKeywordRegistry,
  mapSkill,
  PRESETS,
} from "./map.js";
import { parse, SPINE } from "./parse.js";
import {
  ActivateSkillSchema,
  type KeywordRegistryDraft,
  SkillCatalogEntrySchema,
} from "./schemas.js";

export interface GeneratorOptions {
  readonly corpusRoot: string;
  readonly activationRulesPath: string;
  readonly outDir?: string;
  readonly dryRun?: boolean;
  readonly canaryOnly?: boolean;
}

export interface GeneratorResult {
  readonly skillCount: number;
  readonly validSkills: number;
  readonly activateCount: number;
  readonly validActivate: number;
  readonly keywordEntries: number;
  readonly errors: string[];
  readonly canary: CanaryResult;
  readonly written: string[];
  readonly passed: boolean;
}

function hardSetsForWindow(
  rules: ReturnType<typeof parse>["rawRules"],
  start: number,
  stop: number,
): string[] {
  const stagesInWindow = new Set(SPINE.slice(start - 1, stop));
  const set = new Set<string>();
  for (const r of rules) {
    if (r.hardness === "HARD" && stagesInWindow.has(r.stage as (typeof SPINE)[number])) {
      set.add(r.forceInvokeSkill);
    }
  }
  return [...set].sort();
}

export function runGenerator(opts: GeneratorOptions): GeneratorResult {
  const errors: string[] = [];

  if (opts.canaryOnly) {
    const canary = runCanary();
    return {
      skillCount: 0,
      validSkills: 0,
      activateCount: 0,
      validActivate: 0,
      keywordEntries: 0,
      errors: [],
      canary,
      written: [],
      passed: canary.passed,
    };
  }

  // PARSE
  const { rawSkills, rawRules } = parse(opts.corpusRoot, opts.activationRulesPath);

  // MAP
  const drafts: DraftEntry[] = rawSkills.map(mapSkill);
  const keywords: KeywordRegistryDraft[] = mapKeywordRegistry(drafts, rawRules);
  const activate = PRESETS.map((p) =>
    buildActivateSkill(p, hardSetsForWindow(rawRules, p.start, p.stop)),
  );

  // VALIDATE
  let validSkills = 0;
  for (const d of drafts) {
    const r = SkillCatalogEntrySchema.safeParse(d);
    if (r.success) validSkills++;
    else
      errors.push(
        `skill ${d.id}: ${r.error.issues
          .map((i) => `${i.path.join(".")}:${i.message}`)
          .join("; ")}`,
      );
  }
  let validActivate = 0;
  for (const a of activate) {
    const r = ActivateSkillSchema.safeParse(a);
    if (r.success) validActivate++;
    else
      errors.push(
        `activate ${a.presetId}: ${r.error.issues
          .map((i) => `${i.path.join(".")}:${i.message}`)
          .join("; ")}`,
      );
  }

  // canary (non-vacuity) always runs
  const canary = runCanary();
  if (!canary.passed) errors.push(canary.message);

  const written: string[] = [];
  const passed = errors.length === 0 && canary.passed;

  // EMIT (staging only; skip on dry-run or any error)
  if (!opts.dryRun && passed) {
    // import.meta.url resolves to dist/index.js at runtime.
    // Walk up two levels (dist/ → package root) then into src/generated/
    // so the staging artifact lands in the tracked source tree, not the
    // ephemeral dist/ directory.
    const distDir = dirname(fileURLToPath(import.meta.url));
    const packageRoot = dirname(distDir); // dist/ → package root
    const outDir = opts.outDir ?? join(packageRoot, "src", "generated");
    mkdirSync(outDir, { recursive: true });

    const catalogTs =
      "// AUTO-GENERATED by @harness/generator — do not edit by hand.\n" +
      "// Staging output (architecture D1). Wiring into operational-catalog.ts\n" +
      "// is Tidy-First Slice 2.\n" +
      "import type { SkillCatalogEntry } from " +
      '"@harness/core";\n\n' +
      `export const GENERATED_SKILL_ENTRIES: readonly SkillCatalogEntry[] = ${JSON.stringify(
        drafts,
        null,
        2,
      )} as const;\n`;
    const catalogPath = join(outDir, "skill-catalog-entries.ts");
    writeIfChanged(catalogPath, catalogTs, written);

    const krPath = join(outDir, "keyword-registry.json");
    writeIfChanged(krPath, `${JSON.stringify(keywords, null, 2)}\n`, written);

    const actPath = join(outDir, "activate-skills.json");
    writeIfChanged(actPath, `${JSON.stringify(activate, null, 2)}\n`, written);
  }

  return {
    skillCount: drafts.length,
    validSkills,
    activateCount: activate.length,
    validActivate,
    keywordEntries: keywords.length,
    errors,
    canary,
    written,
    passed,
  };
}

function writeIfChanged(path: string, content: string, written: string[]): void {
  try {
    if (readFileSync(path, "utf8") === content) return;
  } catch {
    /* not present yet */
  }
  writeFileSync(path, content, "utf8");
  written.push(path);
}

// ---- CLI ---------------------------------------------------------------
function arg(argv: string[], name: string): string | undefined {
  const i = argv.indexOf(name);
  return i !== -1 && i + 1 < argv.length ? argv[i + 1] : undefined;
}

export function main(argv: string[]): number {
  const canaryOnly = argv.includes("--canary-only");
  const dryRun = argv.includes("--dry-run");
  const corpusRoot = resolve(arg(argv, "--corpus") ?? "");
  const activationRulesPath = resolve(arg(argv, "--activation-rules") ?? "");
  const outDir = arg(argv, "--out-dir");

  if (!canaryOnly && (!corpusRoot || !activationRulesPath)) {
    process.stderr.write(
      "usage: generate-consommable-artifacts --corpus <dir> --activation-rules <file> [--dry-run] [--canary-only] [--out-dir <dir>]\n",
    );
    return 2;
  }

  const res = runGenerator({
    corpusRoot,
    activationRulesPath,
    dryRun,
    canaryOnly,
    ...(outDir ? { outDir } : {}),
  });

  process.stdout.write(
    `${[
      `skills:   ${res.validSkills}/${res.skillCount} valid`,
      `activate: ${res.validActivate}/${res.activateCount} valid`,
      `keywords: ${res.keywordEntries} entries`,
      `canary:   ${res.canary.message}`,
      `written:  ${res.written.length} file(s)`,
      res.errors.length > 0
        ? `ERRORS (${res.errors.length}):\n  ${res.errors.slice(0, 20).join("\n  ")}`
        : "errors:   0",
      `RESULT:   ${res.passed ? "PASS" : "FAIL"}`,
    ].join("\n")}\n`,
  );
  return res.passed ? 0 : 1;
}
